### ISSUE TITLE
Create about page

### ISSUE THREAD

**Issue by thebiglq12345** [calm-universe/mgt656-spring-2015-project#11]
Includes: your names, each in a span tag with id attribute set to your class nickname

a headshot of you each in an img tag with id="-headshot". This does not have to actually be a picture of you.

**Comment by WSChisholm** [comment]
@thebiglq12345 @jhh3000 Please add your MGT-656 names so that I can include them in the about page, e.g. odd-magpie.

**Comment by jhh3000** [comment]
i am jolly-turtle
